#!/bin/bash

case $1 in

  amd64)
    export VARIANT=alpine-x64
    ;;

  arm64)
    export VARIANT=alpine-arm64
    ;;

  **)
    export VARIANT=linux-armhf
    ;;
esac

echo "I'll use arch ${ARCH}"

curl -sL "https://code.visualstudio.com/sha/download?build=${2}&os=cli-${VARIANT}" --output /tmp/vscode-cli.tar.gz && \
tar -xf /tmp/vscode-cli.tar.gz -C /usr/bin && \
rm /tmp/vscode-cli.tar.gz