#!/bin/bash

case $1 in

  amd64)
    export VARIANT=alpine-x64
    ;;

  arm64)
    export VARIANT=alpine-arm64
    ;;

  **)
    export VARIANT=linux-armhf
    ;;
esac

echo "I'll use build ${2} and variant ${VARIANT}"

curl -sL "https://code.visualstudio.com/sha/download?build=${2}&os=cli-${VARIANT}" --output /tmp/vscode-cli.tar.gz && \
tar -xf /tmp/vscode-cli.tar.gz -C /usr/bin && \
rm /tmp/vscode-cli.tar.gz

if [ -f "/usr/bin/code-insider" ]; then
    mv /usr/bin/code-insider /usr/bin/code
fi
